// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

type Logger_Expecter struct {
	mock *mock.Mock
}

func (_m *Logger) EXPECT() *Logger_Expecter {
	return &Logger_Expecter{mock: &_m.Mock}
}

// Errorw provides a mock function with given fields: _a0, _a1
func (_m *Logger) Errorw(_a0 string, _a1 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	_m.Called(_ca...)
}

// Logger_Errorw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorw'
type Logger_Errorw_Call struct {
	*mock.Call
}

// Errorw is a helper method to define mock.On call
//  - _a0 string
//  - _a1 ...interface{}
func (_e *Logger_Expecter) Errorw(_a0 interface{}, _a1 ...interface{}) *Logger_Errorw_Call {
	return &Logger_Errorw_Call{Call: _e.mock.On("Errorw",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *Logger_Errorw_Call) Run(run func(_a0 string, _a1 ...interface{})) *Logger_Errorw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logger_Errorw_Call) Return() *Logger_Errorw_Call {
	_c.Call.Return()
	return _c
}

// Infow provides a mock function with given fields: _a0, _a1
func (_m *Logger) Infow(_a0 string, _a1 ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _a1...)
	_m.Called(_ca...)
}

// Logger_Infow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infow'
type Logger_Infow_Call struct {
	*mock.Call
}

// Infow is a helper method to define mock.On call
//  - _a0 string
//  - _a1 ...interface{}
func (_e *Logger_Expecter) Infow(_a0 interface{}, _a1 ...interface{}) *Logger_Infow_Call {
	return &Logger_Infow_Call{Call: _e.mock.On("Infow",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *Logger_Infow_Call) Run(run func(_a0 string, _a1 ...interface{})) *Logger_Infow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *Logger_Infow_Call) Return() *Logger_Infow_Call {
	_c.Call.Return()
	return _c
}

// NewLogger creates a new instance of Logger. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t testing.TB) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
